# OS detection
is_omarchy() {
  [[ -f /etc/os-release ]] && . /etc/os-release
  [[ "$ID" == "arch" ]] && command -v hyprctl &>/dev/null
}

section "Shell"

if is_omarchy; then
  # Remove Omarchy's default bash config sourcing — our dotfiles replace it
  if grep -q '^source ~/.local/share/omarchy/default/bash/rc' "$HOME/.bashrc"; then
    sed -i 's|^source ~/.local/share/omarchy/default/bash/rc|# &|' "$HOME/.bashrc"
    ok "Commented out Omarchy default bash rc"
  fi
fi

if [[ -L "$HOME/.bashrc.d" ]]; then
  unlink "$HOME/.bashrc.d"
elif [[ -d "$HOME/.bashrc.d" ]]; then
  rm -rf "$HOME/.bashrc.d"
fi
ln -s "$DOTFILES/bash/" "$HOME/.bashrc.d"
inject_bashrc
ok "bashrc.d linked"

. "$HOME/.bashrc"
touch "$HOME/.cache/hf.env"
ok "Initialized"

cp "$DOTFILES/nvim/lua/_chadrc.lua" "$DOTFILES/nvim/lua/chadrc.lua" 2>/dev/null
cp "$DOTFILES_PRIVATE/ghostty/default.config" "$DOTFILES_PRIVATE/ghostty/config" 2>/dev/null

# ── Symlinks ─────────────────────────────────
section "Symlinks"
. "$DOTFILES/bootstrap/slinks.bash"

# ── Hyprland ──────────────────────────────────
if is_omarchy; then
  section "Hyprland"
  HYPR_DST="$HOME/.config/hypr"
  mkdir -p "$HYPR_DST"

  # hyprland.conf — copy from default template if not present or if generic Hyprland default
  if [[ ! -f "$HYPR_DST/hyprland.conf" ]]; then
    cp "$DOTFILES/hypr/hyprland.default.conf" "$HYPR_DST/hyprland.conf"
    ok "hyprland.conf (created from default)"
  elif head -1 "$HYPR_DST/hyprland.conf" | grep -qi 'autogenerated'; then
    cp -a "$HYPR_DST/hyprland.conf" "$HYPR_DST/hyprland.conf.bak.$(date +%s)"
    cp "$DOTFILES/hypr/hyprland.default.conf" "$HYPR_DST/hyprland.conf"
    warn "hyprland.conf was generic Hyprland default — replaced with template (backup saved)"
  else
    skip "hyprland.conf (already exists)"
  fi

  # Create empty machine/monitor configs if missing (prevents Hyprland source errors)
  for conf in monitors.conf machine.conf; do
    [[ ! -e "$HYPR_DST/$conf" && ! -L "$HYPR_DST/$conf" ]] && touch "$HYPR_DST/$conf"
  done

  # Symlink shared Hyprland configs
  for conf in bindings.conf input.conf autostart.conf hypridle.conf hyprlock.conf hyprsunset.conf; do
    [[ -f "$DOTFILES/hypr/$conf" ]] && slink "$DOTFILES/hypr/$conf" "$HYPR_DST/$conf"
  done
  ok "Hyprland configs linked"
fi

. "$DOTFILES/bootstrap/prompt.bash"
