alias a='create_alias'
alias b='source $DOTFILES/bootstrap.sh'
alias c='clear'
alias d='docker'
alias e='echo'
alias f='fzf'
alias g='git'
alias h='cd $HOME'
alias i='ipython'
# alias j=
# alias k=
alias l='ls --color=auto'
alias m='mv'
alias n='ntl'
alias o="ollama"
alias p='python'
alias q='quiet_background_run'
alias r='source ~/.bashrc'
alias s='slurm'
t() { if [ $# -eq 0 ]; then tmux new-session -A -s "$(basename "$PWD")"; else tmux "$@"; fi; }
alias u='unleash'
alias v='$EDITOR'
# alias w=
# alias x=
# alias y=
# alias z=

# alias A=
# alias B=
# alias C=
# alias D=
# alias E=
# alias F=
# alias G=
# alias H=
# alias I=
# alias J=
# alias K=
# alias L=
# alias M=
# alias N=
# alias O=
# alias P=
# alias Q=
# alias R=
# alias S=
# alias T=
# alias U=
# alias V=
# alias W=
# alias X=
# alias Y=
# alias Z=
